basePath: /
definitions:
  cart.Order:
    properties:
      key:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  description: Cart API
  title: Cart
  version: "1.0"
paths:
  /cart:
    post:
      consumes:
      - application/json
      description: Write order to redis
      parameters:
      - description: body
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/cart.Order'
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
        "503":
          description: Service Unavailable
      summary: Write order
      tags:
      - order
  /cart/{key}:
    get:
      consumes:
      - application/json
      description: Read order from redis
      parameters:
      - description: key
        in: path
        name: key
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cart.Order'
        "404":
          description: Not Found
        "503":
          description: Service Unavailable
      summary: Read order
      tags:
      - order
schemes:
- http
- https
swagger: "2.0"
